//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PINProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registracija
    {
        public int id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> Kurs_id { get; set; }
        public Nullable<int> Grupa_id { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual Kurs Kurs { get; set; }
    }
}
